# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d23f22f3adad83fbe81a32cce35b3cd6083fd98c6ca51b886c602a5539f4589bd2f6876525ea67755529e60ce93a1c01646c4a77d2b82f2095ec8ae0ed779c4

test:
  secret_key_base: e05e776cc47e6c48692a23b99c8a8a819f341772ff93ffaeb41d4ac89d2be29ede3cf97350086597b0d0fefd3a0e2fed2011f584e69e34fd3a40593c183aebbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
